
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public ConfigGoods.TbGoods TbGoods {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbGoods = new ConfigGoods.TbGoods(loader("configgoods_tbgoods"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbGoods.ResolveRef(this);
    }
}

}
