
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.ConfigGoods
{ 
    [System.Flags]
    public enum GoodsType
    {
        武器 = 1,
        防具 = 2,
        道具 = 3,
        坐骑 = 4,
    }

} 

