
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.ConfigGoods
{
public partial class TbGoods
{
    private readonly System.Collections.Generic.Dictionary<int, ConfigGoods.Goods> _dataMap;
    private readonly System.Collections.Generic.List<ConfigGoods.Goods> _dataList;
    
    public TbGoods(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ConfigGoods.Goods>();
        _dataList = new System.Collections.Generic.List<ConfigGoods.Goods>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ConfigGoods.Goods _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = ConfigGoods.Goods.DeserializeGoods(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.GoodsId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ConfigGoods.Goods> DataMap => _dataMap;
    public System.Collections.Generic.List<ConfigGoods.Goods> DataList => _dataList;

    public ConfigGoods.Goods GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ConfigGoods.Goods Get(int key) => _dataMap[key];
    public ConfigGoods.Goods this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

